# .travis.yml

# Specify the language and Python versions
language: python
python:
  - "3.9"  # Use a stable Python version (3.13 is not yet stable)
dist: focal
os: linux

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

# Run checks and tests
script:
  - black --check .  # Validate code formatting with black
  - flake8 .  # Check code style with flake8
  - coverage run --source=mysite manage.py test mysite  # Run tests with coverage
  - coverage report  # Print coverage report
  - coverage xml  # Generate coverage XML for coveralls

# Report coverage to coveralls
after_success:
  - coveralls --service=travis-pro

# Deploy to AWS Elastic Beanstalk upon successful tests
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"  # Update to your AWS region
  app: "django-tutorial"  # Update to your EB application name
  env: "django-poll"  # Update to your EB environment name
  # bucket: $AWS_S3_BUCKET  # Update to your S3 bucket name
  # bucket_path: "django-poll"  # Update to your S3 bucket path
  cleanup: false
  on:
    branch: main  # Update to your main branch name (e.g., main, master)

# Notifications (optional)
notifications:
  email:
    on_success: never
    on_failure: always